from enum import Enum

class MCVer(Enum):
    def __cmp__(self, other): ...
    def __le__(self, other): ...
    def __lt__(self, other): ...
    def __ge__(self, other): ...
    def __gt__(self, other): ...
    JE_1_19_1: int
    JE_1_19_2: int
