from enum import Enum

class BreakLevel(Enum):
    PASS: BreakLevel
    CONTINUE: BreakLevel
    BREAK: BreakLevel
    RETURN: BreakLevel
    RAISE: BreakLevel

    @property
    def value(self) -> int: ...
    @staticmethod
    def from_value(value: BreakLevel | int) -> BreakLevel: ...
    def __eq__(self, other: BreakLevel): ...
    def __lt__(self, other: BreakLevel): ...
    def __le__(self, other: BreakLevel): ...
    def __gt__(self, other: BreakLevel): ...
    def __ge__(self, other: BreakLevel): ...
